
package zhangbin.cumt.item_crm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.bos_crm.cumt.zhangbin/")
@XmlSeeAlso({
   // ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activeCustomer", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.ActiveCustomer")
    @ResponseWrapper(localName = "activeCustomerResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.ActiveCustomerResponse")
    public void activeCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns zhangbin.cumt.bos_crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephoneAndPassword", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindByTelephoneAndPassword")
    @ResponseWrapper(localName = "findByTelephoneAndPasswordResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindByTelephoneAndPasswordResponse")
    public Customer findByTelephoneAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<zhangbin.cumt.bos_crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssociation", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindNotAssociation")
    @ResponseWrapper(localName = "findNotAssociationResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindNotAssociationResponse")
    public List<Customer> findNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<zhangbin.cumt.bos_crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindByTelephoneResponse")
    public List<Customer> findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomers2FixedArea", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.AssignCustomers2FixedArea")
    @ResponseWrapper(localName = "assignCustomers2FixedAreaResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.AssignCustomers2FixedAreaResponse")
    public void assignCustomers2FixedArea(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<zhangbin.cumt.bos_crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByEmail", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindByEmail")
    @ResponseWrapper(localName = "findByEmailResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindByEmailResponse")
    public List<Customer> findByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<zhangbin.cumt.bos_crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<zhangbin.cumt.bos_crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAssociation", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindAssociation")
    @ResponseWrapper(localName = "findAssociationResponse", targetNamespace = "http://service.bos_crm.cumt.zhangbin/", className = "zhangbin.cumt.bos_crm.service.FindAssociationResponse")
    public List<Customer> findAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
